package com.gep;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @gep
//  @ File Name : AbsoluteFitness.java
//  @ Date : 2013/4/5
//  @ Author : @shenzhan
//
//




public class AbsoluteFitness extends FitnessFunction {


	@Override
	public void GetFitness(Population Pop, double[][] Data, double[] Fitness) {
		// TODO Auto-generated method stub
		
	}
	

}
